FROM node:lts-alpine
WORKDIR '/app'
# tells docker what specified dependencies to install into a node_module folder, but only on the temporary container
COPY ./package.json ./
RUN npm install
COPY . .
# default commands that we always use for applications created from React App
# Default start command, will start up a development server. So that is why this is not a good thing for a production environment
CMD ["npm", "run", "start"]