# Yes this is an intentional file. Not here by accident. So yes there are two nginx containers in CHECKPOINT206
# This nginx file is Listening on port 3000, the other nginx file is Listening on port 80.
# When we are running in development mode, docker-compose.yml will have set up volumes and portmapping so that 
# http requests are coming from localhost 3050:80 port mapping, and port 3000 http requests are coming from client>nginx>default.conf,(could as well be client>foo>default.conf).
# When we are running in production mode, http requests from port 3000 are coming from a production server.
# Either way, for any http requests that come from port 3000, this nginx will serve up the React production files, see line 41.
# 
# fyi. we use nginx because it is a production level web server (unlike Reacts dev server) 
#    There are two nginx containers in CHECKPOINT206. One nginx is at the root level and one nginx is at the client level (where we are at now).
# So here, nginx is acting as a web server for the client React application. It has a default.conf that has only one routing rule
# and is Listening on port 3000, because we say that below at line 37. 
#
# This client>nginx>default.conf is Listening for traffic coming from the root level nginx server, that is forwarded to this upstream client, 
# To recap, http request are originating from locahost:3050:80 to get us to the root level ingnx server, and from there the React development server is
# listening on port 3000, and the index.html and index.js files (React aplication) are served up to the browser.
#
# It turns out that no matter if this process is running in Development or Production, we are always listening on port 3000.
#
#      Development scenario
# We will be using the docker-compose.yml file for our development work. (The docker-compose.yml file uses the Dockerfile.dev files).
# This means the client will be using the React development server and the React development server listens on port 3000 by default. 
# The docker-compose.yml file has port mappings of 3050:80. 
# Also, the docker-compose.yml file defines the upstream client to be listening on port 3000.
# So http://localhost:3050 will kick things off.
# So, traffic comes in to 3050, goes to 80, goes to the client at port 3000 that the React development server listens on,
# and the index.html and index.js files (React aplication) are served up to the browser.
# 
#    Production scenario
# We are not using the docker-compose.yml file.
# We therefore are not using the Dockerfile.dev files.
# We are now using the Dockerfile files (production files).
# The browser sends traffic to the outside nginx server (that is listening on port 80). The outside nginx server's routing rules (root>nginx>default.conf) send traffic to the upstream client
# that will be using nginx as the server (instead of the React development server). This second nginx is listening on port 3000 because of line 37 below. That is where routing rules are found 
# and the index.html and index.js files (React aplication) are served up to the browser.
#  
#
server {
  listen 3000;

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html;
  }
}