FROM node:14.14.0-alpine
WORKDIR '/app'
# tells docker what specified dependencies to install into a node_module folder, but only on the temporary container
COPY ./package.json ./  
RUN npm install
COPY . .

# for some reason he says to use nodemon for the development server 122 Dockerizing Geneic Node Apps video 1:17
# nodemon is a command line tool that can be used to automatically reload the entire project anytime source code in the project changes, and then restart the web app
CMD ["npm", "run", "dev"]