FROM node:14.14.0-alpine
WORKDIR '/app'
# tells docker what specified dependencies to install into a node_module folder, but only on the temporary container
COPY ./package.json ./  
RUN npm install
COPY . .

# for some reason he says to use nodemon for the develompnet server 122 Dockerizing Geneic Node Apps video 1:17
CMD ["npm", "run", "dev"]